@base_url = http://localhost

@port = 3000

@url = {{base_url}}:{{port}}

@user_api = {{url}}/manager

GET {{user_api}}/getmanager HTTP/1.1
###
GET {{user_api}}/getmanager/2 HTTP/1.1

###
GET {{user_api}}/getmanagerbyusername HTTP/1.1
Content-Type: application/json

{
    "username": "sirapop1",
    "email": "siraphop5@gmail.com"
}
###

POST {{user_api}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "sirapop1119",
    "password": "12345"
}

###
POST {{user_api}}/register HTTP/1.1
Content-Type: application/json

{
    "name": "สิรภพ สุขใจ1",
    "shop_name": "ร้านปันสุข",
    "username": "sirapop111111",
    "password": "12345",
    "email": "siraphop11124@gmail.com",
    "phone": "0821534458"
}
###
PUT {{user_api}}/editmanager/3 HTTP/1.1
Content-Type: application/json

{
    "name": "แสนดี สีใจก๋า",
    "shop_name": "ร้านแสนดี",
    "username": "sandeeshop",
    "password": "88888888",
    "email": "sandee123@gmail.com",
    "phone": "0817786652"
}
###

DELETE  {{user_api}}/deletemanager/4 HTTP/1.1