@base_url = http://localhost

@port = 5000

@url = {{base_url}}:{{port}}

@user_api = {{url}}/manager

@admin_api = {{url}}/admin

@product_api  = {{url}}/product

@ordered_api = {{url}}/ordered

@owner_api = {{url}}/owner

@bearerTokenManager = Bearer {{login.response.body.token}}

@bearerTokenAdmin = Bearer {{loginadmin.response.body.token}}

@bearerTokenOwner = Bearer {{loginowner.response.body.token}}

// Manager
# @name login
POST {{user_api}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "sukjaishop",
    "password": "12121212"
}
###
GET {{user_api}}/checktoken HTTP/1.1
Authorization: {{bearerTokenManager}}

###
POST {{user_api}}/forget HTTP/1.1
Content-Type: application/json

{
    "email":"kndew666@gmail.com"
}

###
POST {{user_api}}/register HTTP/1.1
Content-Type: application/json

{
    "name": "อนุพงศ์",
    "shop_name": "ร้านอนุพงศ์",
    "username": "anupong",
    "password": "11111za",
    "email": "kndew666@gmail.com",
    "phone": "0871123654"
}

###
PUT {{user_api}}/editmanager HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: application/json

{
    "name": "อนุพงศ์ สูตรเลข",
    "shop_name": "ร้านอนุพงศ์",
    "password": "11111za",
    "email": "anupongsutlek022@gmail.com",
    "phone": "0871123654"
}
###
GET {{product_api}}/getproduct HTTP/1.1
Authorization: {{bearerTokenManager}}

###
GET {{product_api}}/getproduct/1 HTTP/1.1
Authorization: {{bearerTokenManager}}

###
GET {{product_api}}/getproductbyname HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: application/json

{
    "nameproduct": "กะเพราหมูกรอบ"
}
###
POST {{product_api}}/register HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nameproduct"

ยำปลาทู
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="priceproduct"

60
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="demo.png"
Content-Type: image/png

< ./demo01.JPG
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
PUT {{product_api}}/updateproduct/2 HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nameproduct"

กะเพราผัดเผ็ด
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="priceproduct"

50
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="demo.png"
Content-Type: image/png

< ./demo02.JPG
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
DELETE {{{{product_api}}}}/deleteproduct/3 HTTP/1.1
Authorization: {{bearerTokenManager}}
###
POST {{admin_api}}/registeradmin HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: application/json

{
    "nameadmin": "admindew188",
    "phoneadmin": "0955786621",
    "emailadmin": "nongaek1@gmail.com",
    "usernameadmin": "admindeww1",
    "passwordadmin": "123456za"
}

###
GET {{admin_api}}/getadmin HTTP/1.1
Authorization: {{bearerTokenManager}}

###
GET {{admin_api}}/getadmin/2 HTTP/1.1
Authorization: {{bearerTokenManager}}
###
GET {{admin_api}}/getadminbyname HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: application/json

{
    "nameadmin": "admindew1"
}

###
DELETE {{admin_api}}/deleteadmin/5 HTTP/1.1
Authorization: {{bearerTokenManager}}

###
GET {{ordered_api}}/getorderall HTTP/1.1
Authorization: {{bearerTokenManager}}

###
GET {{ordered_api}}/sumorderall HTTP/1.1
Authorization: {{bearerTokenManager}}
###
GET {{ordered_api}}/getorderbybill/2 HTTP/1.1
Authorization: {{bearerTokenManager}}

###
GET {{ordered_api}}/getordertoday HTTP/1.1
Authorization: {{bearerTokenManager}}

###
GET {{ordered_api}}/sumordertoday HTTP/1.1
Authorization: {{bearerTokenManager}}

###

GET {{ordered_api}}/getorderyesterday HTTP/1.1
Authorization: {{bearerTokenManager}}
###

GET {{ordered_api}}/sumorderyesterday HTTP/1.1
Authorization: {{bearerTokenManager}}
###

GET {{ordered_api}}/sumorderweek HTTP/1.1
Authorization: {{bearerTokenManager}}
###

GET {{ordered_api}}/getorderweek HTTP/1.1
Authorization: {{bearerTokenManager}}
###

GET {{ordered_api}}/getordermonth HTTP/1.1
Authorization: {{bearerTokenManager}}

###

GET {{ordered_api}}/sumordermonth HTTP/1.1
Authorization: {{bearerTokenManager}}
###

GET {{ordered_api}}/sumorderyear HTTP/1.1
Authorization: {{bearerTokenManager}}
###

GET {{ordered_api}}/getorderyear HTTP/1.1
Authorization: {{bearerTokenManager}}
###

GET {{ordered_api}}/sumorder2year HTTP/1.1
Authorization: {{bearerTokenManager}}
###

GET {{ordered_api}}/getorder2year HTTP/1.1
Authorization: {{bearerTokenManager}}

###
POST {{ordered_api}}/getorderbyselect HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: application/json

{
    "date": "2023-05-11"
}
###
POST {{ordered_api}}/getorderbynamecustomer HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: application/json

{
    "namecustomer": "น้องฟัง"
}
###
POST {{ordered_api}}/sumorderbyselect HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: application/json

{
    "date": "2023-05-11"
}

###
POST {{ordered_api}}/getorderbyselectbetweenday HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: application/json

{
    "datestart": "2023-05-03",
    "datestop": "2023-05-12"
}
###
POST {{ordered_api}}/sumorderbyselectbetweenday HTTP/1.1
Authorization: {{bearerTokenManager}}
Content-Type: application/json

{
    "datestart": "2023-05-03",
    "datestop": "2023-05-12"
}

###

DELETE {{ordered_api}}/deleteordered/2 HTTP/1.1
Authorization: {{bearerTokenManager}}

//###########################################################################################################################################
//###########################################################################################################################################
//###########################################################################################################################################


// Admin
###
GET {{product_api}}/getproduct HTTP/1.1
Authorization: {{bearerTokenAdmin}}

###
GET {{product_api}}/getproduct/1 HTTP/1.1
Authorization: {{bearerTokenAdmin}}

###
GET {{user_api}}/checktoken HTTP/1.1
Authorization: {{bearerTokenAdmin}}

###
# @name loginadmin
POST {{admin_api}}/loginadmin HTTP/1.1
Content-Type: application/json

{
    "usernameadmin": "admindew",
    "passwordadmin": "123456za"
}


###
PUT {{admin_api}}/updateadmin HTTP/1.1
Authorization: {{bearerTokenAdmin}}
Content-Type: application/json

{
    "nameadmin": "แอดมินฟัง",
    "phoneadmin": "0955786865",
    "emailadmin": "adminaek@gmail.com",
    "usernameadmin": "admindew",
    "passwordadmin": "123456za"
}

###
POST {{ordered_api}}/addorder HTTP/1.1
Authorization: {{bearerTokenAdmin}}
Content-Type: application/json

 [

    {
        "menunumber": 1,
        "nameordered": "ยำไข่เยี่ยวม้า",
        "priceordered": 60,
        "countordered": 1,
        "namecustomer": "น้องฟัง",
        "tablenumber": 1
    }
    ,
    {
        "menunumber": 2,
        "nameordered": "แกงเขียวหวานหมา",
        "priceordered": 60,
        "countordered": 1,
        "namecustomer": "น้องเอก",
        "tablenumber": 1
    }
    ,
    {
        "menunumber": 3,
        "nameordered": "ผัดผงกะหรี่",
        "priceordered": 80,
        "countordered": 3,
        "namecustomer": "น้องอาม",
        "tablenumber": 1
    }
    
]



//###########################################################################################################################################
//###########################################################################################################################################
//###########################################################################################################################################




// OWNER
###
GET {{user_api}}/getmanager HTTP/1.1
###
POST {{user_api}}/forget-password HTTP/1.1
Content-Type: application/json

{
    "password": "1111112",
    "password2": "1111112"
}
###
GET {{user_api}}/getmanager/2 HTTP/1.1

###
GET {{user_api}}/checktoken HTTP/1.1
Authorization: {{bearerTokenOwner}}
###
POST {{user_api}}/signup HTTP/1.1

###
POST {{ordered_api}}/sumorderallbyusername HTTP/1.1
Authorization: {{bearerTokenOwner}}
Content-Type: application/json

{
    "username": "anupong"
}
###
POST {{user_api}}/forget HTTP/1.1
Content-Type: application/json

{
    "email": "anupongsutlek022@gmail.com"
}
// anupongsutlek022@gmail.com // owner
// Kndew666@gmail.com //manager
// kongfang095@gmail.com // admin
###
# @name loginowner
POST {{owner_api}}/loginowner HTTP/1.1
Content-Type: application/json

{
    "username": "anpongsutlek",
    "password": "0917076980za"
}

###
PUT {{owner_api}}/updateowner HTTP/1.1
Authorization: {{bearerTokenOwner}}
Content-Type: application/json

{
    "namemanagerapp": "เอก",
    "username": "anpongsutlek",
    "password": "0917076980za",
    "email": "adminaek@gmail.com",
    "mobile": "0955786621"
}
###
DELETE {{user_api}}/deletemanager/4 HTTP/1.1